### ISSUE TITLE
Prepare Good Readme , Installation documentation

### ISSUE THREAD

**Issue by kshitijrajsharma** [hotosm/fAIr#113]
This issue is about documentation plan is to prepare a best way to communicate what fair is what it does , its potential and current stage so that people landing to github will get the gist idea 💡 ! Also we can separate installation doc for developers, also we can explain other smaller modules that fair is using such as fair utilities

**Comment by petya-kangalova** [comment]
Adding a bit more info about the documentation: 

- [ ] Complete the community checklist https://github.com/hotosm/fAIr/community 
Detailed documentation targeted for : 
- [ ] Initial users who knows nothing about fair and landed into github site ! 
- [ ]  Technical users who knows about ML but not about fAIr and interested on knowing more
- [ ] Developers : Installation docs ( this can be separated)

**Comment by petya-kangalova** [comment]
Adding photos here on general workflow to be used in the docs.
![Flowchart (3)](https://github.com/hotosm/fAIr/assets/98902727/4d6c3261-6c4c-4dd8-8b03-a69556252b03)
![Flowchart (2)](https://github.com/hotosm/fAIr/assets/98902727/5f1c8589-657d-4196-9e27-c3548bd59ab0)

**Comment by kshitijrajsharma** [comment]
Reference : https://www.hotosm.org/tech-blog/hot-tech-talks-fair/

**Comment by petya-kangalova** [comment]
Reference to presentation that can be used for history/background of fAIr in readme file: https://docs.google.com/presentation/d/1kR2Gezh3yOhEZBSjtoJR37rJ1JX9Q3m6T43BO55puIU/edit#slide=id.g17a6951e02b_0_26

**Comment by petya-kangalova** [comment]
Thanks to those of you who joined the [HOT Open Tech and Inno session](https://docs.google.com/document/d/1ni4Kxto7_n5-Gs9SGppcBr-kHsIyzCIl1PWwXFCcaHQ/edit#) earlier today where I talked about this specific issue! Some people asked about example of similar docs from other repo- FMTM is one you can use for reference, where we have used [Wiki ](https://github.com/hotosm/fmtm/wiki). Please comment on the issue if you are interested in collaborating and helping us with creating documentation!

**Comment by chrischank** [comment]
Hi @petya-kangalova and @kshitijrajsharma  sorry for missing voluntary session again, think I finally found the documentation issue pages, are there currently a table for tracking what needs or not needs to be documented still? How can we slot  ourselves in, do we create a temporary doc branches when writing readme etc...

**Comment by kshitijrajsharma** [comment]
@chrischank  Not yet ! Initial plan is to let user know all about fAIr what we trying to achieve and what our current position is ! We can start by creating fork / branch start with .md file , Can modify existing readme.md pr introduce new .md file whichever is easy to read when user lands to fAIr github repo !

**Comment by chrischank** [comment]
I guess what you would want is a readme.md per application or module right with a template and then that readme.md is assigned to a volunteer or a staff to work on based on understanding of the existing code?

**Comment by chrischank** [comment]
![image](https://github.com/hotosm/fAIr/assets/36608720/416cbc20-784c-4041-a697-c0d0b657922f)

So far I only see these .md so far

**Comment by petya-kangalova** [comment]
looping in @neelimagoogly  as she is currently working on the docs https://github.com/hotosm/fAIr/pull/127. The idea is to create them as Github Wiki Pages. I am speaking with Neelima at 13:00UTC today about this- @chrischank  you're welcome to join if you're free to discuss collaborating on this.

**Comment by petya-kangalova** [comment]
After discussion with @neelimagoogly  and @chrischank  we agreed to split into three issues:
https://github.com/hotosm/fAIr/issues/128
https://github.com/hotosm/fAIr/issues/129
https://github.com/hotosm/fAIr/issues/130

I am closing this one as work will continue in the above issues.
