### ISSUE TITLE
local docker compse up error

### ISSUE THREAD

**Issue by pzs-pzs** [hotosm/fAIr#159]
**Describe the bug**
`
AttributeError: module 'cv2.gapi.wip.draw' has no attribute 'Text'
`

**To Reproduce**
1.docker compose build
2.docker compose up

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by kshitijrajsharma** [comment]
- Should be fixed by #163

**Comment by kshitijrajsharma** [comment]
- Fixed by #167
