### ISSUE TITLE
Ability to delete AOI

### ISSUE THREAD

**Issue by petya-kangalova** [hotosm/fAIr#183]
**Is your feature request related to a problem? Please describe.**
Ability to delete an area of interest from frontend on the right hand side where AOI are listed.

**Describe the solution you'd like**
Currently @omranlm  had to delete from backend. 

**Describe alternatives you've considered**
Add an option to delete under List of Area of Interest.
![image](https://github.com/hotosm/fAIr/assets/98902727/002c1c14-70fc-4540-92ee-5ec9e2d7c2a2)

**Additional context**
Feedback shared as part of testing with LAC Hub.

**Comment by kshitijrajsharma** [comment]
Delete button on left side of the map will delete the Area of Interest from Frontend , It is quite hard right now I think adding a remove button will be super userful on right side of the screen where we have AOI Card along with zoom to !

**Comment by petya-kangalova** [comment]
@kshitijrajsharma  exactly that! I have now updated my issue to clarify I meant right hand side. Thank you!
