### ISSUE TITLE
Time out error when fetching feedback AOI labels 

### ISSUE THREAD

**Issue by omranlm** [hotosm/fAIr#185]
**Describe the bug**
The API response is time out and the AOI status is stuck as Running, end point tested /label/feedback/osm/fetch with parameter 26

**To Reproduce**
1. Go to ['Feedback page for any model'](https://fair-dev.hotosm.org/ai-models/82/338/feedback)
2. Create a new Feedback AOI
3. Click on fetch OSM labels for a feedback AOI
4. See the error in the console log or wait and the status of the AOI will be always Running.

**Expected behavior**
Return a clear error if no labels or an error happens and change the AOI status to fail in case of issues.

**Screenshots**
![image](https://github.com/hotosm/fAIr/assets/39491329/2908932b-6b88-448d-a655-da6916687651)

 - Browser chrome

**Comment by omranlm** [comment]
@kshitijrajsharma more analysis for this as it is due to Database down for the raw data API, it would be great to have a better error handling when the raw data API is not responding

**Comment by kshitijrajsharma** [comment]
Agreed , let's keep this issue open I will add validation !
