### ISSUE TITLE
Bug in labels viewing in the feedback page

### ISSUE THREAD

**Issue by omranlm** [hotosm/fAIr#197]
**Describe the bug**
Labels are showing out of no where without an AOI similar to the screenshot below

**To Reproduce**
1. Go to a model feedback page
2. navigate to some feedback AOIs
3. zoom in to show the labels
4. some labels would show outside 

**Expected behavior**
Labels should show only for AOIs assigned to specific training ID 

**Screenshots**
![image](https://github.com/hotosm/fAIr/assets/39491329/a0a39266-3eb6-49b2-8af4-821c26c2a939)

**Comment by kshitijrajsharma** [comment]
One question , I believe label should be shown only for the Feedback AOI assigned to specific training ID ? right ? @omranlm
