### ISSUE TITLE
Semiduplicate contribution instruction

### ISSUE THREAD

**Issue by Ettrig** [hotosm/fAIr#212]
fAIr/CONTRIBUTING.md and fAIr/docs/Contribution.md have the same intention and largely the same content. This duplication causes some confusion and some extra maintenance work. 

Solution: merge Contribution into CONTRIBUTING and remove Contribution.

**Comment by kshitijrajsharma** [comment]
Thanks Rolf for this ! Yes and agreed

**Comment by Ettrig** [comment]
I can do this. Please merge PR #201 first.
