### ISSUE TITLE
Show proper message when Raw data API is down

### ISSUE THREAD

**Issue by omranlm** [hotosm/fAIr#219]
**Describe the bug**
the AOI fetch OSM data button when clicked, AOI status is stuck kas RUNNING and never changes

**To Reproduce**
1. Go to AOI in any dataset
2. Click on fetch OSM data
3. Wait for some time and RNNING status won't change 

**Expected behavior**
Showing a proper error message when Raw data API is failing retuning data 

**Screenshots**
![image](https://github.com/hotosm/fAIr/assets/39491329/100d0b4e-e5b0-4be7-ac0e-17f0b6cbd350)

**Comment by omranlm** [comment]
CC: @kshitijrajsharma

**Comment by kshitijrajsharma** [comment]
@omranlm  from API side it is already raising error when` raw-data-api `is down , You might need to look for the API status to display the message in frontend
