### ISSUE TITLE
Only accepted features should be included in the download data

### ISSUE THREAD

**Issue by omranlm** [hotosm/fAIr#223]
**Describe the bug**
In the mapping page, only accepted features should be included in the download .. or clearly declare that the download would include all predicated features 

**To Reproduce**
1. Go to mapping page, for example https://fair-dev.hotosm.org/start-mapping/120
2. Click on run prediction
3. Scroll down see the download as geojson button under options section
4. Download the data and visualize it in QGIS and it will include all features

**Expected behavior**
We should have the selected features only downloaded
Another option is to clearly say it is downloading all data

**Screenshots**
![image](https://github.com/hotosm/fAIr/assets/39491329/af16d38e-5a0c-4e95-ba4a-92ed7f7b686d)

**Comment by omranlm** [comment]
CC @kshitijrajsharma

**Comment by natrimmer** [comment]
I'd like to ask clarifying questions with an example.

Here is a predication with some accepted features:
<img width="769" alt="Screenshot 2024-07-10 at 14 54 20" src="https://github.com/hotosm/fAIr/assets/75459551/0d61d2e2-7401-4673-a26f-67f9db5c2b72">

And here is the downloaded GeoJSON from that prediction represented in QGIS:
<img width="1042" alt="Screenshot 2024-07-10 at 14 56 32" src="https://github.com/hotosm/fAIr/assets/75459551/cd09fab8-77db-4348-9d1a-899241604157">

@omranlm is suggesting that if there are accepted features within the prediction that the GeoJSON downloaded when rendered should look like this:
<img width="1188" alt="Screenshot 2024-07-10 at 15 03 37" src="https://github.com/hotosm/fAIr/assets/75459551/58da73be-51d7-4988-9b2d-11ffe7fa0c3f">

Is that a correct understanding of the problem? As for the exact feature, maybe it could end up being two buttons. One for all predicted features represented in the GeoJSON, and once the first feature is accepted an additional button displays for downloaded just the accepted feaetures in GeoJSON format.

**Comment by kshitijrajsharma** [comment]
> I'd like to ask clarifying questions with an example.
> 
> 
> 
> Here is a predication with some accepted features:
> 
> <img width="769" alt="Screenshot 2024-07-10 at 14 54 20" src="https://github.com/hotosm/fAIr/assets/75459551/0d61d2e2-7401-4673-a26f-67f9db5c2b72">
> 
> 
> 
> And here is the downloaded GeoJSON from that prediction represented in QGIS:
> 
> <img width="1042" alt="Screenshot 2024-07-10 at 14 56 32" src="https://github.com/hotosm/fAIr/assets/75459551/cd09fab8-77db-4348-9d1a-899241604157">
> 
> 
> 
> @omranlm is suggesting that if there are accepted features within the prediction that the GeoJSON downloaded when rendered should look like this:
> 
> <img width="1188" alt="Screenshot 2024-07-10 at 15 03 37" src="https://github.com/hotosm/fAIr/assets/75459551/58da73be-51d7-4988-9b2d-11ffe7fa0c3f">
> 
> 
> 
> Is that a correct understanding of the problem? As for the exact feature, maybe it could end up being two buttons. One for all predicted features represented in the GeoJSON, and once the first feature is accepted an additional button displays for downloaded just the accepted feaetures in GeoJSON format.
> 
> 

That's correct understanding!

**Comment by omranlm** [comment]
The 2 buttons idea sounds like a better solution.

We also got community feedback while piloting with HOT hubs to define an area of interest and run prediction for the whole area then share predictions as geojson, so that could be a 3rd button that takes are of interest and returns geojson (it might need queuing as response time would depend on the size of the area of interest)

**Comment by natrimmer** [comment]
So three different GeoJSON export options:

1. Defined areas of interests within the dataset
2. After running a prediction, all predicted features
3. After accepting a feature, all accepted features
