### ISSUE TITLE
Typo in Docker Installation Guide

### ISSUE THREAD

**Issue by nwekealex65** [hotosm/fAIr#235]
The documentation for the Docker installation guide (https://github.com/hotosm/fAIr/blob/master/docs/Docker-installation.md) contains a typo in the section regarding cloning the repository. The word "Clonse" is used instead of "clone." This typo could potentially cause confusion for users following the installation instructions. Let's correct this typo to ensure the accuracy and clarity of the documentation.

**Comment by kshitijrajsharma** [comment]
Go ahead and feel free to raise PR

**Comment by nwekealex65** [comment]
@kshitijrajsharma I just created a pull request https://github.com/nwekealex65/fAIr/pull/3 review so I can make the PR directly to the master branch

**Comment by nwekealex65** [comment]
@kshitijrajsharma I didn't get a response from you. I fixed the numbering issue, any other fixes to be made please let me know
