### ISSUE TITLE
Show proper duration for failed trainings

### ISSUE THREAD

**Issue by omranlm** [hotosm/fAIr#297]
**Describe the bug**
Show empty duration or dash - when there is not finished_at date for a training record to avoid those non sense duration as in the screenshot below 

**To Reproduce**
1. Go to a failed training that doesn't have a finished_at value
2. see the duration calculation which is calculating wrong value

**Expected behavior**
Show a "-" or empty value when training is failed and there is not finished_at value

**Screenshots**

![image](https://github.com/user-attachments/assets/d9f91dcc-9092-4751-ae7d-bb962f55f5fc)

**Comment by omranlm** [comment]
@jeafreezy

**Comment by jeafreezy** [comment]
PR up for this @omranlm . #298

**Comment by jeafreezy** [comment]
> @jeafreezy

Great catch! Thanks.
