### ISSUE TITLE
Model Details Crashed During Enhancement

### ISSUE THREAD

**Issue by jeafreezy** [hotosm/fAIr#307]
**Describe the bug**
One of the models (https://fair-dev.hotosm.org/ai-models/165/details), perhaps others exist, crashes during enhancement.

**To Reproduce**
1. Go to https://fair-dev.hotosm.org/ai-models/165/details
2. See error

**Expected behavior**
Based on the current implementation logic, the user should see the model details page for enhancement.

**Screenshots**

![Image](https://github.com/user-attachments/assets/500e4a3c-4971-4a03-b137-bb8a64a7d560)

**Desktop (please complete the following information):**
 - OS: Macbook Pro M3.
 - Browser : Chrome
 - Version: Version 131.0.6778.86 (Official Build) (arm64)

**Comment by jeafreezy** [comment]
Fixed in #308

**Comment by jeafreezy** [comment]
Reopening because it seems it hasn't been deployed.

cc: @kshitijrajsharma

**Comment by jeafreezy** [comment]
Now deployed.

**Comment by kshitijrajsharma** [comment]
Thanks
