### ISSUE TITLE
Build API end point returns error when multi AOIs exists

### ISSUE THREAD

**Issue by omranlm** [hotosm/fAIr#31]
When more than 1 AOI are associated with a dataset, the /dataset/image/build end point fails with the following error
![image](https://user-images.githubusercontent.com/39491329/209130057-883e81ff-20a1-479a-8fc6-30dea371ce09.png)

@kshitijrajsharma

**Comment by kshitijrajsharma** [comment]
oh ! Yeah I think i know the issue , I will include the fix on my next PR .
