### ISSUE TITLE
In the dataset view, we need to pass dataset ID

### ISSUE THREAD

**Issue by omranlm** [hotosm/fAIr#43]
As in the following, we need to pass the dataset ID as the /label/ with bbox filter is getting labels from other datasets which are created in the same location 

Also no need for uniqe key on the OSM id in the labels table

![image](https://user-images.githubusercontent.com/39491329/210367645-ecf55071-703e-4e61-8fe5-c256d9efdc62.png)

**Comment by kshitijrajsharma** [comment]
Related API ENDPOINT : 
```
https://API_URL/api/v1/label/?in_bbox=36.425656457456974,-0.770674651699887,36.42940886786881,-0.768529078055876
````

**Comment by kshitijrajsharma** [comment]
Related endpoint should be filterable by Dataset ID along with bbox !
