### ISSUE TITLE
Redirect http to https  for stage url 

### ISSUE THREAD

**Issue by kshitijrajsharma** [hotosm/fAIr#51]

**Comment by mohammadareeb95** [comment]
Hey @kshitijrajsharma! Could you please provide some more reference on where exactly to make changes? Thanks alot

**Comment by kshitijrajsharma** [comment]
Hi @mohammadareeb95 Thank you for your interest ,  I plan to describe issues and cleanup repo by First week of April , Will comeback and keep you in the Loop
