### ISSUE TITLE
Dataset Build is failing on Big Datasets 

### ISSUE THREAD

**Issue by kshitijrajsharma** [hotosm/fAIr#63]
Refer to training 101 for dataset 1 model 1 on dev server 
![image](https://user-images.githubusercontent.com/36752999/216053815-98bb9087-5abc-4de4-ace8-c73cc3248ca8.png)

**Comment by omranlm** [comment]
Seems like dataset is not fully built as the geojson not found 
![image](https://user-images.githubusercontent.com/39491329/216065436-5c3920d1-30eb-47ef-8b41-e7de24ea2771.png)

RefL flower [Task 82e56520-beb1-4bce-b63f-9a051a428fe5](http://fair-dev.hotosm.org:5000/task/82e56520-beb1-4bce-b63f-9a051a428fe5)

**Comment by kshitijrajsharma** [comment]
Yes, I guess I  have figured out the issue ,API call can't be extended on https , when there is huge dataset it will take couple of minutes to complete the task when Api response can't wait for that long !  we need some background service / use exisiting celery to build dataset

**Comment by kshitijrajsharma** [comment]
It is so hard to debug why system failed but here are my initial debug results : 
1 ) Gunicorn kills itself and restart immediately after some point when there is a huge request 
2) I can confirm that #50 this issue is not causing the problem , I am being able to recreate the bug for huge osm data download endpoint too where behavior is same and also i have tested the image downloading without threads same issue persists and only persist with huge datasets which take longer time to process 
3) Through debugging system errors , I figured out some of the request are killed because of the larger time out caused by the API 
![image](https://user-images.githubusercontent.com/36752999/216282628-9c697cdc-c134-4c10-bc5e-b0812f517a30.png)
 Until now I can't reproduce the issue on my local , local is http server and it can wait forever so my suspicion is it is happening for https

**Comment by kshitijrajsharma** [comment]
**Check for Possible resource Outage :** 
Resources usage for those huge datasets is not much , I have dropped the Memory usage for downloading images using threads in this commit https://github.com/hotosm/fAIr/commit/f780dd92b47a15b4ce40e4b67afbab10516bc335 
So far shutdown is not caused by resources in all my test case scenarios 
![image](https://user-images.githubusercontent.com/36752999/216285355-52c7d6e1-8a4a-44b0-87c1-6a14125bb285.png)
