### ISSUE TITLE
BUG : When Clicked on Map Editing Options Map Moves 

### ISSUE THREAD

**Issue by kshitijrajsharma** [hotosm/fAIr#88]
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/36752999/230288934-62ad49e1-31e6-48b2-b1b8-7b77c97ff58d.png">
When clicked on left map editing layers , + - polygon creator , Map is shifting upwards

**Comment by omranlm** [comment]
We changed the style to avoid this and it is closed already
